##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

###############################################################################
#                             Global settings                                  #
###############################################################################

server_names = ['local-doh']

listen_addresses = ['127.0.0.1:53']

max_clients = 250

###############################################################################
#                            Server Selection                                  #
###############################################################################

ipv4_servers = true

ipv6_servers = false

dnscrypt_servers = false

doh_servers = true

odoh_servers = false

require_dnssec = false

require_nolog = true

require_nofilter = true

disabled_server_names = []

###############################################################################
#                           Connection Settings                                #
###############################################################################

force_tcp = false

http3 = false

http3_probe = false

timeout = 5000

keepalive = 30

###############################################################################
#                                Logging                                       #
###############################################################################

## Log level (0-6, default: 2 - 0 is very verbose, 6 only contains fatal errors)

log_level = 0

###############################################################################
#                           Certificate Management                             #
###############################################################################

cert_refresh_delay = 240

###############################################################################
#                            Startup & Network                                 #
###############################################################################

bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']

ignore_system_dns = true

netprobe_timeout = 60

netprobe_address = '9.9.9.9:53'

###############################################################################
#                                 Filters                                      #
###############################################################################

block_ipv6 = false

block_unqualified = true

block_undelegated = true

reject_ttl = 10

###############################################################################
#                                DNS Cache                                     #
###############################################################################

cache = false

###############################################################################
#                              Query logging                                   #
###############################################################################

[query_log]

file = 'query-local-doh.log'

format = 'tsv'

###############################################################################
#                           IP Encryption                                      #
###############################################################################

[ip_encryption]

algorithm = "none"

key = ""

###############################################################################
#                            Monitoring UI                                     #
###############################################################################

[monitoring_ui]

enabled = false

###############################################################################
#                            Static entries                                    #
###############################################################################

[static]
  [static.local-doh]
  stamp = 'sdns://AgcAAAAAAAAADjEyNy4wLjAuMTo4NDQzAA4xMjcuMC4wLjE6ODQ0MwovZG5zLXF1ZXJ5'